// design-system/nuxt-app/components/WebUI.vue
<script setup>
// Ported from pages/web-ui.jsx `WebUI` — the shell that switches pages.
import { ref } from 'vue'

const page = ref('dashboard')
const tx = ref(null)

const selectTx = (t) => { tx.value = t; page.value = 'detail' }
const onNav = (k) => { page.value = k; tx.value = null }
</script>

<template>
  <div class="webui-shell">
    <div class="app" :data-screen-label="page">
      <Sidebar :current="page === 'detail' ? 'payouts' : page" @nav="onNav" />
      <div class="main">
        <Topbar />
        <Dashboard v-if="page === 'dashboard'" @select-tx="selectTx" @go-to-payouts="page = 'payouts'" />
        <Payouts v-if="page === 'payouts'" @select-tx="selectTx" />
        <PayoutDetail v-if="page === 'detail'" :tx="tx" @back="page = 'payouts'" />
        <Collections v-if="page === 'collections'" @select-tx="selectTx" />
        <Recipients v-if="page === 'recipients'" />
        <Team v-if="page === 'team'" />
        <Settings v-if="page === 'settings'" />
        <div v-if="page === 'balances'" class="page" :style="{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '400px' }">
          <div :style="{ textAlign: 'center', color: 'var(--fg-3)' }">
            <Icon name="wallet" :style="{ width: '32px', height: '32px', color: 'var(--fg-4)' }" />
            <div :style="{ marginTop: '12px', fontSize: '14px' }">Balances page — to be built.</div>
          </div>
        </div>
        <div v-if="page === 'developers'" class="page" :style="{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '400px' }">
          <div :style="{ textAlign: 'center', color: 'var(--fg-3)' }">
            <Icon name="code-2" :style="{ width: '32px', height: '32px', color: 'var(--fg-4)' }" />
            <div :style="{ marginTop: '12px', fontSize: '14px' }">Developers / API keys page — to be built.</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// design-system/pages/web-ui.jsx
// Design System · Web UI Kit page — renders the full web app shell inline.
// Pulls Sidebar / Topbar / page components from the web_app kit JSX files.

const WebUI = () => {
  const [page, setPage] = React.useState('dashboard');
  const [tx, setTx] = React.useState(null);

  React.useEffect(() => {
    requestAnimationFrame(() => { if (window.lucide) window.lucide.createIcons(); });
  }, [page]);

  const selectTx = (t) => { setTx(t); setPage('detail'); };

  return (
    <div className="webui-shell">
      <div className="app" data-screen-label={page}>
        <Sidebar current={page === 'detail' ? 'payouts' : page} onNav={(k) => { setPage(k); setTx(null); }} />
        <div className="main">
          <Topbar />
          {page === 'dashboard'   && <Dashboard onSelectTx={selectTx} onGoToPayouts={() => setPage('payouts')} />}
          {page === 'payouts'     && <Payouts onSelectTx={selectTx} />}
          {page === 'detail'      && <PayoutDetail tx={tx} onBack={() => setPage('payouts')} />}
          {page === 'collections' && <Collections onSelectTx={selectTx} />}
          {page === 'recipients'  && <Recipients />}
          {page === 'team'        && <Team />}
          {page === 'settings'    && <Settings />}
          {page === 'balances'    && (
            <div className="page" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: 400 }}>
              <div style={{ textAlign: 'center', color: 'var(--fg-3)' }}>
                <i data-lucide="wallet" style={{ width: 32, height: 32, color: 'var(--fg-4)' }}></i>
                <div style={{ marginTop: 12, fontSize: 14 }}>Balances page — to be built.</div>
              </div>
            </div>
          )}
          {page === 'developers' && (
            <div className="page" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: 400 }}>
              <div style={{ textAlign: 'center', color: 'var(--fg-3)' }}>
                <i data-lucide="code-2" style={{ width: 32, height: 32, color: 'var(--fg-4)' }}></i>
                <div style={{ marginTop: 12, fontSize: 14 }}>Developers / API keys page — to be built.</div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

window.WebUI = WebUI;
